<?php
/**
 * Anime editorial media and presentation helpers.
 *
 * @package InfoSecNexus
 */

declare(strict_types=1);

namespace InfoSecNexus\Theme\Anime_Design;

/**
 * Return the allowed editorial asset definitions.
 *
 * @return array<string,array{file:string,alt:string}>
 */
function assets(): array {
	return array(
		'hero'     => array(
			'file' => 'hero-cyber-sentinel.webp',
			'alt'  => __( 'Cybersecurity analyst monitoring a holographic shield and threat map', 'infosecnexus' ),
		),
		'windows'  => array(
			'file' => 'featured-windows-security.webp',
			'alt'  => __( 'Security analyst reviewing a Windows workstation alert', 'infosecnexus' ),
		),
		'network'  => array(
			'file' => 'featured-network-security.webp',
			'alt'  => __( 'Network defender inspecting a protected data connection', 'infosecnexus' ),
		),
		'linux'    => array(
			'file' => 'featured-linux-devops.webp',
			'alt'  => __( 'DevOps engineer securing a Linux deployment pipeline', 'infosecnexus' ),
		),
		'critical' => array(
			'file' => 'featured-critical-cve.webp',
			'alt'  => __( 'Critical vulnerability warning above a compromised server core', 'infosecnexus' ),
		),
		'cloud'    => array(
			'file' => 'featured-cloud-security.webp',
			'alt'  => __( 'Cloud security engineer protecting connected infrastructure', 'infosecnexus' ),
		),
		'ai'       => array(
			'file' => 'featured-ai-security.webp',
			'alt'  => __( 'AI security researcher analyzing a protected neural model', 'infosecnexus' ),
		),
		'team'     => array(
			'file' => 'about-contact-team.webp',
			'alt'  => __( 'InfoSecNexus security team collaborating in an operations room', 'infosecnexus' ),
		),
	);
}

/**
 * Normalize an editorial asset key.
 *
 * @param string $key Candidate asset key.
 * @return string Normalized asset key.
 */
function normalize_key( string $key ): string {
	return array_key_exists( $key, assets() ) ? $key : 'hero';
}

/**
 * Return an editorial asset URL.
 *
 * @param string $key   Editorial asset key.
 * @param int    $width Desired source width.
 * @return string Asset URL.
 */
function asset_url( string $key, int $width = 1280 ): string {
	$key        = normalize_key( $key );
	$definition = assets()[ $key ];
	$width      = 640 === $width ? 640 : 1280;

	return get_template_directory_uri() . '/assets/anime/webp-' . $width . '/' . $definition['file'];
}

/**
 * Return editorial asset alt text.
 *
 * @param string $key Editorial asset key.
 * @return string Localized alt text.
 */
function asset_alt( string $key ): string {
	$key = normalize_key( $key );
	return assets()[ $key ]['alt'];
}

/**
 * Infer the strongest topic-specific visual for a post.
 *
 * @param int $post_id Post ID.
 * @return string Editorial asset key.
 */
function post_asset_key( int $post_id ): string {
	$post = get_post( $post_id );
	if ( ! $post instanceof \WP_Post ) {
		return 'hero';
	}

	$categories = wp_get_post_categories(
		$post_id,
		array(
			'fields' => 'all',
		)
	);
	$terms      = array();
	if ( is_wp_error( $categories ) ) {
		$categories = array();
	}
	foreach ( $categories as $category ) {
		if ( $category instanceof \WP_Term ) {
			$terms[] = $category->slug;
			$terms[] = $category->name;
		}
	}

	$haystack = strtolower( $post->post_title . ' ' . implode( ' ', $terms ) );

	$rules = array(
		'windows' => '/\b(windows|microsoft|winsock|win32|sharepoint|exchange|active directory|defender|bitlocker|ntlm)\b/i',
		'network' => '/\b(network|cisco|sonicwall|fortinet|fortios|palo alto|firewall|router|vpn|loadmaster|progress kemp|f5|checkpoint|check point)\b/i',
		'linux'   => '/\b(linux|ubuntu|debian|red hat|rhel|kernel|devops|docker|kubernetes|jenkins|teamcity|gitlab|github actions|pipeline)\b/i',
		'cloud'   => '/\b(cloud|aws|amazon web services|google cloud|gcp|azure cloud|iam|storage bucket)\b/i',
		'ai'      => '/\b(ai security|artificial intelligence|machine learning|llm|model|agentic|openai|anthropic|langflow|prompt injection)\b/i',
	);

	foreach ( $rules as $key => $pattern ) {
		if ( preg_match( $pattern, $haystack ) ) {
			return $key;
		}
	}

	if ( str_contains( $haystack, 'critical-cves' ) || preg_match( '/\bcve-\d{4}-\d{4,}\b/i', $haystack ) ) {
		return 'critical';
	}

	return 'hero';
}

/**
 * Return a manually selected featured attachment.
 *
 * Artwork generated by the newsroom may be superseded by the visual system,
 * but an attachment selected in the editor always remains authoritative.
 *
 * @param int $post_id Post ID.
 * @return int Attachment ID, or zero when the theme artwork should be used.
 */
function manual_featured_image_id( int $post_id ): int {
	$thumbnail_id = (int) get_post_thumbnail_id( $post_id );
	if ( $thumbnail_id < 1 ) {
		return 0;
	}

	$generated_for = (int) get_post_meta( $thumbnail_id, '_infosecnexus_artwork_post_id', true );
	return $post_id === $generated_for ? 0 : $thumbnail_id;
}

/**
 * Build escaped HTML attributes.
 *
 * @param array<string,mixed> $attrs Attributes.
 */
function html_attributes( array $attrs ): string {
	$output = '';
	foreach ( $attrs as $name => $value ) {
		if ( false === $value || null === $value || ( '' === $value && 'alt' !== $name ) ) {
			continue;
		}
		if ( true === $value ) {
			$output .= ' ' . esc_attr( (string) $name );
			continue;
		}
		$output .= ' ' . esc_attr( (string) $name ) . '="' . esc_attr( (string) $value ) . '"';
	}
	return $output;
}

/**
 * Render a responsive static editorial asset.
 *
 * @param string              $key   Editorial asset key.
 * @param array<string,mixed> $attrs Image attributes.
 */
function asset_image( string $key, array $attrs = array() ): string {
	$key   = normalize_key( $key );
	$attrs = array_merge(
		array(
			'alt'      => asset_alt( $key ),
			'class'    => 'isn-editorial-image',
			'width'    => 1280,
			'height'   => 720,
			'loading'  => 'lazy',
			'decoding' => 'async',
			'sizes'    => '(max-width: 720px) calc(100vw - 32px), 640px',
		),
		$attrs
	);

	$attrs['src']    = asset_url( $key );
	$attrs['srcset'] = asset_url( $key, 640 ) . ' 640w, ' . asset_url( $key, 1280 ) . ' 1280w';

	return '<img' . html_attributes( $attrs ) . '>';
}

/**
 * Return post media data for preloads and social metadata.
 *
 * @param int $post_id Post ID.
 * @return array{url:string,srcset:string,width:int,height:int,alt:string,attachment_id:int,key:string}
 */
function post_image_data( int $post_id ): array {
	$attachment_id = manual_featured_image_id( $post_id );
	if ( $attachment_id > 0 ) {
		$source = wp_get_attachment_image_src( $attachment_id, 'full' );
		$url    = is_array( $source ) ? (string) $source[0] : '';
		$width  = is_array( $source ) ? (int) $source[1] : 1280;
		$height = is_array( $source ) ? (int) $source[2] : 720;
		$alt    = (string) get_post_meta( $attachment_id, '_wp_attachment_image_alt', true );
		$alt    = '' !== trim( $alt ) ? $alt : get_the_title( $post_id );
		$srcset = (string) wp_get_attachment_image_srcset( $attachment_id, 'full' );

		return compact( 'url', 'srcset', 'width', 'height', 'alt', 'attachment_id' ) + array( 'key' => '' );
	}

	$key = post_asset_key( $post_id );
	return array(
		'url'           => asset_url( $key ),
		'srcset'        => asset_url( $key, 640 ) . ' 640w, ' . asset_url( $key, 1280 ) . ' 1280w',
		'width'         => 1280,
		'height'        => 720,
		'alt'           => asset_alt( $key ),
		'attachment_id' => 0,
		'key'           => $key,
	);
}

/**
 * Render the best post image while preserving editor-selected attachments.
 *
 * @param int                 $post_id Post ID.
 * @param array<string,mixed> $attrs   Image attributes.
 * @param string              $size    WordPress attachment size.
 */
function post_image( int $post_id, array $attrs = array(), string $size = 'large' ): string {
	$attachment_id = manual_featured_image_id( $post_id );
	$attrs         = array_merge(
		array(
			'class'    => 'isn-editorial-image',
			'loading'  => 'lazy',
			'decoding' => 'async',
			'sizes'    => '(max-width: 720px) calc(100vw - 32px), 640px',
		),
		$attrs
	);

	if ( $attachment_id > 0 ) {
		return (string) wp_get_attachment_image( $attachment_id, $size, false, $attrs );
	}

	return asset_image( post_asset_key( $post_id ), $attrs );
}

/**
 * Render the hero poster and deferred motion layer.
 *
 * The static image is always present and remains the LCP candidate. JavaScript
 * adds the MP4 source only after the window load event.
 *
 * @param int $post_id Optional post ID whose manual featured image overrides animation.
 */
function hero_media( int $post_id = 0 ): void {
	$manual_image_id = $post_id > 0 ? manual_featured_image_id( $post_id ) : 0;
	$poster_data     = $manual_image_id > 0 ? post_image_data( $post_id ) : array(
		'url' => asset_url( 'hero' ),
		'alt' => asset_alt( 'hero' ),
	);
	?>
	<figure class="anime-hero-media<?php echo $manual_image_id > 0 ? ' anime-hero-media--static' : ''; ?>"<?php echo $manual_image_id > 0 ? '' : ' data-animated-hero'; ?>>
		<?php
		$poster_attrs = array(
			'class'         => 'anime-hero-media__poster isn-editorial-image',
			'loading'       => 'eager',
			'fetchpriority' => 'high',
			'decoding'      => 'async',
			'sizes'         => '(max-width: 760px) calc(100vw - 32px), (max-width: 1180px) 64vw, 820px',
		);
		$hero_markup  = $manual_image_id > 0
			? post_image( $post_id, $poster_attrs, 'large' )
			: asset_image( 'hero', $poster_attrs );
		// Both helpers return complete image markup with escaped attributes.
		echo $hero_markup; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		?>
		<?php if ( 0 === $manual_image_id ) : ?>
			<video class="anime-hero-media__video" muted loop playsinline preload="none" width="1280" height="720" poster="<?php echo esc_url( (string) $poster_data['url'] ); ?>" aria-hidden="true" data-src="<?php echo esc_url( get_template_directory_uri() . '/assets/anime/animation/hero-cyber-sentinel-loop.mp4' ); ?>"></video>
			<button class="anime-hero-media__toggle isn-control" type="button" aria-pressed="false" aria-label="<?php esc_attr_e( 'Play hero animation', 'infosecnexus' ); ?>">
				<span class="anime-hero-media__play" aria-hidden="true">&#9654;</span>
				<span class="anime-hero-media__pause" aria-hidden="true">&#10074;&#10074;</span>
			</button>
		<?php endif; ?>
	</figure>
	<?php
}

/**
 * Return the visual key for an archive or category slug.
 *
 * @param string $slug Archive or category slug.
 * @return string Editorial asset key.
 */
function term_asset_key( string $slug ): string {
	$slug = sanitize_key( $slug );
	if ( str_contains( $slug, 'windows' ) ) {
		return 'windows';
	}
	if ( str_contains( $slug, 'network' ) || str_contains( $slug, 'web-security' ) ) {
		return 'network';
	}
	if ( str_contains( $slug, 'linux' ) || str_contains( $slug, 'devops' ) || str_contains( $slug, 'tutorial' ) ) {
		return 'linux';
	}
	if ( str_contains( $slug, 'cloud' ) ) {
		return 'cloud';
	}
	if ( str_contains( $slug, 'artificial' ) || str_contains( $slug, 'ai-' ) ) {
		return 'ai';
	}
	if ( str_contains( $slug, 'critical' ) || str_contains( $slug, 'cve' ) ) {
		return 'critical';
	}

	return 'hero';
}

/**
 * Return whether a post should receive the critical card treatment.
 *
 * @param int $post_id Post ID.
 * @return bool Whether the post is critical.
 */
function is_critical_post( int $post_id ): bool {
	$severity = strtoupper( (string) get_post_meta( $post_id, '_infosecnexus_live_severity', true ) );
	return in_array( $severity, array( 'CRITICAL', 'KNOWN EXPLOITED' ), true ) || has_category( 'critical-cves', $post_id );
}

/**
 * Remove the seeded page hero from rendered content.
 *
 * Special page templates promote its WordPress-managed copy into the real page
 * header. Removing only the rendered duplicate keeps the editor content and
 * shortcodes untouched in the database.
 *
 * @param string $content Saved page content.
 * @return string Content without the duplicate hero.
 */
function without_seeded_page_hero( string $content ): string {
	$pattern = '/<section\b[^>]*class=(?:"[^"]*\bisnx-page-hero\b[^"]*"|\'[^\']*\bisnx-page-hero\b[^\']*\')[^>]*>.*?<\/section>/is';
	$clean   = preg_replace( $pattern, '', $content, 1 );

	return is_string( $clean ) ? $clean : $content;
}

/**
 * Return supporting copy from a WordPress-managed page.
 *
 * @param int $post_id Page ID.
 * @return string Introductory copy.
 */
function page_intro( int $post_id ): string {
	$excerpt = trim( (string) get_post_field( 'post_excerpt', $post_id ) );
	if ( '' !== $excerpt ) {
		return wp_strip_all_tags( $excerpt );
	}

	$content = (string) get_post_field( 'post_content', $post_id );
	if ( ! preg_match_all( '/<p\b([^>]*)>(.*?)<\/p>/is', $content, $matches, PREG_SET_ORDER ) ) {
		return '';
	}

	foreach ( $matches as $match ) {
		$attributes = strtolower( (string) $match[1] );
		if ( str_contains( $attributes, 'isnx-page-kicker' ) ) {
			continue;
		}

		$copy = trim( wp_strip_all_tags( (string) $match[2] ) );
		if ( '' !== $copy ) {
			return $copy;
		}
	}

	return '';
}

/**
 * Return the seeded hero heading for a WordPress-managed special page.
 *
 * @param int $post_id Page ID.
 * @return string Hero heading.
 */
function page_hero_title( int $post_id ): string {
	$content = (string) get_post_field( 'post_content', $post_id );
	if ( ! preg_match( '/<section\b[^>]*class=(?:"[^"]*\bisnx-page-hero\b[^"]*"|\'[^\']*\bisnx-page-hero\b[^\']*\')[^>]*>.*?<h2\b[^>]*>(.*?)<\/h2>/is', $content, $match ) ) {
		return '';
	}

	return trim( wp_strip_all_tags( (string) $match[1] ) );
}

/**
 * Ensure the Contact page contains the bundled secure form.
 *
 * Older editor content can retain the visual panel while WordPress strips the
 * form element. Replace that incomplete panel at render time without changing
 * the saved page content or duplicating an already valid secure form.
 *
 * @param string $content Rendered page content.
 * @return string Content with the secure form panel.
 */
function ensure_secure_contact_form( string $content ): string {
	if ( str_contains( $content, 'isnx-contact-form' ) || ! shortcode_exists( 'infosecnexus_contact_form' ) ) {
		return $content;
	}

	$form = do_shortcode( '[infosecnexus_contact_form]' );
	if ( ! str_contains( $form, 'isnx-contact-form' ) ) {
		return $content;
	}

	$panel  = '<section class="isnx-contact-panel" id="contact-form">';
	$panel .= '<div><h2>' . esc_html__( 'Write to us', 'infosecnexus' ) . '</h2>';
	$panel .= '<p>' . esc_html__( 'Tell us what needs review, what changed, and how we can reach you. Clear context helps us route corrections, security tips, and collaboration requests faster.', 'infosecnexus' ) . '</p>';
	$panel .= '<div class="isnx-alert-note"><strong>' . esc_html__( 'Before you send:', 'infosecnexus' ) . '</strong> ';
	$panel .= esc_html__( 'do not include passwords, private keys, tokens, or sensitive credentials.', 'infosecnexus' ) . '</div></div>';
	$panel .= $form . '</section>';

	$count   = 0;
	$updated = preg_replace(
		'#<section\b[^>]*class=(["\'])[^"\']*\bisnx-contact-panel\b[^"\']*\1[^>]*>.*?</section>#is',
		$panel,
		$content,
		1,
		$count
	);

	if ( is_string( $updated ) && 1 === $count ) {
		return $updated;
	}

	return $content . $panel;
}

/**
 * Add stable IDs to second-level content headings.
 *
 * Existing editor-authored IDs remain authoritative. Duplicate IDs receive a
 * deterministic fallback so table-of-contents links stay unique.
 *
 * @param string $content Rendered article content.
 * @return string Content with stable heading IDs.
 */
function add_heading_ids( string $content ): string {
	if ( '' === trim( $content ) || ! str_contains( strtolower( $content ), '<h2' ) || ! class_exists( '\\WP_HTML_Tag_Processor' ) ) {
		return $content;
	}

	$processor = new \WP_HTML_Tag_Processor( $content );
	$used_ids  = array();
	$position  = 0;

	while ( $processor->next_tag( array( 'tag_name' => 'H2' ) ) ) {
		++$position;
		$current_id = $processor->get_attribute( 'id' );
		$current_id = is_string( $current_id ) ? trim( $current_id ) : '';

		if ( '' === $current_id || isset( $used_ids[ $current_id ] ) ) {
			$base_id    = 'section-' . $position;
			$current_id = $base_id;
			$suffix     = 2;
			while ( isset( $used_ids[ $current_id ] ) ) {
				$current_id = $base_id . '-' . $suffix;
				++$suffix;
			}
			$processor->set_attribute( 'id', $current_id );
		}

		$used_ids[ $current_id ] = true;
	}

	return $processor->get_updated_html();
}

/**
 * Return the second-level heading outline used by article navigation.
 *
 * @param string $content Rendered article content.
 * @return array<int,array{id:string,label:string}>
 */
function heading_outline( string $content ): array {
	$content = add_heading_ids( $content );
	if ( ! preg_match_all( '/<h2\b([^>]*)>(.*?)<\/h2>/is', $content, $matches, PREG_SET_ORDER ) ) {
		return array();
	}

	$outline = array();
	foreach ( $matches as $match ) {
		if ( ! preg_match( '/\bid\s*=\s*(["\'])(.*?)\1/is', (string) $match[1], $id_match ) ) {
			continue;
		}

		$id    = trim( wp_specialchars_decode( (string) $id_match[2], ENT_QUOTES ) );
		$label = trim( wp_specialchars_decode( wp_strip_all_tags( (string) $match[2] ), ENT_QUOTES ) );
		if ( '' !== $id && '' !== $label ) {
			$outline[] = array(
				'id'    => $id,
				'label' => $label,
			);
		}
	}

	return $outline;
}
